// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4e1UvhgoFKH9OfCC8ihg97MnKUiUixCk',
    appId: '1:24412117070:web:51e09c843275f9c7508b1f',
    messagingSenderId: '24412117070',
    projectId: 'car-rental-app-8ce0a',
    authDomain: 'car-rental-app-8ce0a.firebaseapp.com',
    storageBucket: 'car-rental-app-8ce0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdIEntkH62QB8Y-JLIyjioGkS-fnzUUI',
    appId: '1:24412117070:android:4ca446f95093a1dd508b1f',
    messagingSenderId: '24412117070',
    projectId: 'car-rental-app-8ce0a',
    storageBucket: 'car-rental-app-8ce0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRSfkV5lppkvWkqciX0rr_oOR25Q3-0k8',
    appId: '1:24412117070:ios:db455396227917e9508b1f',
    messagingSenderId: '24412117070',
    projectId: 'car-rental-app-8ce0a',
    storageBucket: 'car-rental-app-8ce0a.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRSfkV5lppkvWkqciX0rr_oOR25Q3-0k8',
    appId: '1:24412117070:ios:db455396227917e9508b1f',
    messagingSenderId: '24412117070',
    projectId: 'car-rental-app-8ce0a',
    storageBucket: 'car-rental-app-8ce0a.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4e1UvhgoFKH9OfCC8ihg97MnKUiUixCk',
    appId: '1:24412117070:web:5dd5e543b2fa53db508b1f',
    messagingSenderId: '24412117070',
    projectId: 'car-rental-app-8ce0a',
    authDomain: 'car-rental-app-8ce0a.firebaseapp.com',
    storageBucket: 'car-rental-app-8ce0a.firebasestorage.app',
  );

}